// Generated by the protocol buffer compiler.  DO NOT EDIT!

package emu.grasscutter.net.proto;
// source: TowerBriefDataNotify.proto

public final class TowerBriefDataNotifyOuterClass {
  private TowerBriefDataNotifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TowerBriefDataNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TowerBriefDataNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 tower_schedule_id = 1;</code>
     * @return The towerScheduleId.
     */
    int getTowerScheduleId();

    /**
     * <code>uint32 next_schedule_change_time = 2;</code>
     * @return The nextScheduleChangeTime.
     */
    int getNextScheduleChangeTime();

    /**
     * <code>uint32 total_star_num = 3;</code>
     * @return The totalStarNum.
     */
    int getTotalStarNum();

    /**
     * <code>uint32 last_floor_index = 4;</code>
     * @return The lastFloorIndex.
     */
    int getLastFloorIndex();

    /**
     * <code>uint32 last_level_index = 5;</code>
     * @return The lastLevelIndex.
     */
    int getLastLevelIndex();

    /**
     * <code>bool is_finished_entrance_floor = 6;</code>
     * @return The isFinishedEntranceFloor.
     */
    boolean getIsFinishedEntranceFloor();

    /**
     * <code>uint32 schedule_start_time = 7;</code>
     * @return The scheduleStartTime.
     */
    int getScheduleStartTime();
  }
  /**
   * Protobuf type {@code TowerBriefDataNotify}
   */
  public static final class TowerBriefDataNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TowerBriefDataNotify)
      TowerBriefDataNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TowerBriefDataNotify.newBuilder() to construct.
    private TowerBriefDataNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TowerBriefDataNotify() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TowerBriefDataNotify();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TowerBriefDataNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              towerScheduleId_ = input.readUInt32();
              break;
            }
            case 16: {

              nextScheduleChangeTime_ = input.readUInt32();
              break;
            }
            case 24: {

              totalStarNum_ = input.readUInt32();
              break;
            }
            case 32: {

              lastFloorIndex_ = input.readUInt32();
              break;
            }
            case 40: {

              lastLevelIndex_ = input.readUInt32();
              break;
            }
            case 48: {

              isFinishedEntranceFloor_ = input.readBool();
              break;
            }
            case 56: {

              scheduleStartTime_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TowerBriefDataNotifyOuterClass.internal_static_TowerBriefDataNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TowerBriefDataNotifyOuterClass.internal_static_TowerBriefDataNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.class, TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.Builder.class);
    }

    /**
     * Protobuf enum {@code TowerBriefDataNotify.CmdId}
     */
    public enum CmdId
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0, 0),
      /**
       * <code>ENET_IS_RELIABLE = 1;</code>
       */
      ENET_IS_RELIABLE(2, 1),
      /**
       * <code>CMD_ID = 2449;</code>
       */
      CMD_ID(3, 2449),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>ENET_CHANNEL_ID = 0;</code>
       */
      public static final CmdId ENET_CHANNEL_ID = NONE;
      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>ENET_CHANNEL_ID = 0;</code>
       */
      public static final int ENET_CHANNEL_ID_VALUE = 0;
      /**
       * <code>ENET_IS_RELIABLE = 1;</code>
       */
      public static final int ENET_IS_RELIABLE_VALUE = 1;
      /**
       * <code>CMD_ID = 2449;</code>
       */
      public static final int CMD_ID_VALUE = 2449;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdId valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CmdId forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return ENET_IS_RELIABLE;
          case 2449: return CMD_ID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CmdId>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CmdId> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CmdId>() {
              public CmdId findValueByNumber(int number) {
                return CmdId.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (index == -1) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.getDescriptor().getEnumTypes().get(0);
      }

      private static final CmdId[] VALUES = getStaticValuesArray();
      private static CmdId[] getStaticValuesArray() {
        return new CmdId[] {
          NONE, ENET_CHANNEL_ID, ENET_IS_RELIABLE, CMD_ID, 
        };
      }
      public static CmdId valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CmdId(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TowerBriefDataNotify.CmdId)
    }

    public static final int TOWER_SCHEDULE_ID_FIELD_NUMBER = 1;
    private int towerScheduleId_;
    /**
     * <code>uint32 tower_schedule_id = 1;</code>
     * @return The towerScheduleId.
     */
    @java.lang.Override
    public int getTowerScheduleId() {
      return towerScheduleId_;
    }

    public static final int NEXT_SCHEDULE_CHANGE_TIME_FIELD_NUMBER = 2;
    private int nextScheduleChangeTime_;
    /**
     * <code>uint32 next_schedule_change_time = 2;</code>
     * @return The nextScheduleChangeTime.
     */
    @java.lang.Override
    public int getNextScheduleChangeTime() {
      return nextScheduleChangeTime_;
    }

    public static final int TOTAL_STAR_NUM_FIELD_NUMBER = 3;
    private int totalStarNum_;
    /**
     * <code>uint32 total_star_num = 3;</code>
     * @return The totalStarNum.
     */
    @java.lang.Override
    public int getTotalStarNum() {
      return totalStarNum_;
    }

    public static final int LAST_FLOOR_INDEX_FIELD_NUMBER = 4;
    private int lastFloorIndex_;
    /**
     * <code>uint32 last_floor_index = 4;</code>
     * @return The lastFloorIndex.
     */
    @java.lang.Override
    public int getLastFloorIndex() {
      return lastFloorIndex_;
    }

    public static final int LAST_LEVEL_INDEX_FIELD_NUMBER = 5;
    private int lastLevelIndex_;
    /**
     * <code>uint32 last_level_index = 5;</code>
     * @return The lastLevelIndex.
     */
    @java.lang.Override
    public int getLastLevelIndex() {
      return lastLevelIndex_;
    }

    public static final int IS_FINISHED_ENTRANCE_FLOOR_FIELD_NUMBER = 6;
    private boolean isFinishedEntranceFloor_;
    /**
     * <code>bool is_finished_entrance_floor = 6;</code>
     * @return The isFinishedEntranceFloor.
     */
    @java.lang.Override
    public boolean getIsFinishedEntranceFloor() {
      return isFinishedEntranceFloor_;
    }

    public static final int SCHEDULE_START_TIME_FIELD_NUMBER = 7;
    private int scheduleStartTime_;
    /**
     * <code>uint32 schedule_start_time = 7;</code>
     * @return The scheduleStartTime.
     */
    @java.lang.Override
    public int getScheduleStartTime() {
      return scheduleStartTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (towerScheduleId_ != 0) {
        output.writeUInt32(1, towerScheduleId_);
      }
      if (nextScheduleChangeTime_ != 0) {
        output.writeUInt32(2, nextScheduleChangeTime_);
      }
      if (totalStarNum_ != 0) {
        output.writeUInt32(3, totalStarNum_);
      }
      if (lastFloorIndex_ != 0) {
        output.writeUInt32(4, lastFloorIndex_);
      }
      if (lastLevelIndex_ != 0) {
        output.writeUInt32(5, lastLevelIndex_);
      }
      if (isFinishedEntranceFloor_ != false) {
        output.writeBool(6, isFinishedEntranceFloor_);
      }
      if (scheduleStartTime_ != 0) {
        output.writeUInt32(7, scheduleStartTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (towerScheduleId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, towerScheduleId_);
      }
      if (nextScheduleChangeTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, nextScheduleChangeTime_);
      }
      if (totalStarNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, totalStarNum_);
      }
      if (lastFloorIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, lastFloorIndex_);
      }
      if (lastLevelIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, lastLevelIndex_);
      }
      if (isFinishedEntranceFloor_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isFinishedEntranceFloor_);
      }
      if (scheduleStartTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, scheduleStartTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TowerBriefDataNotifyOuterClass.TowerBriefDataNotify)) {
        return super.equals(obj);
      }
      TowerBriefDataNotifyOuterClass.TowerBriefDataNotify other = (TowerBriefDataNotifyOuterClass.TowerBriefDataNotify) obj;

      if (getTowerScheduleId()
          != other.getTowerScheduleId()) return false;
      if (getNextScheduleChangeTime()
          != other.getNextScheduleChangeTime()) return false;
      if (getTotalStarNum()
          != other.getTotalStarNum()) return false;
      if (getLastFloorIndex()
          != other.getLastFloorIndex()) return false;
      if (getLastLevelIndex()
          != other.getLastLevelIndex()) return false;
      if (getIsFinishedEntranceFloor()
          != other.getIsFinishedEntranceFloor()) return false;
      if (getScheduleStartTime()
          != other.getScheduleStartTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOWER_SCHEDULE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTowerScheduleId();
      hash = (37 * hash) + NEXT_SCHEDULE_CHANGE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getNextScheduleChangeTime();
      hash = (37 * hash) + TOTAL_STAR_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getTotalStarNum();
      hash = (37 * hash) + LAST_FLOOR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getLastFloorIndex();
      hash = (37 * hash) + LAST_LEVEL_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getLastLevelIndex();
      hash = (37 * hash) + IS_FINISHED_ENTRANCE_FLOOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinishedEntranceFloor());
      hash = (37 * hash) + SCHEDULE_START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleStartTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TowerBriefDataNotifyOuterClass.TowerBriefDataNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TowerBriefDataNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TowerBriefDataNotify)
        TowerBriefDataNotifyOuterClass.TowerBriefDataNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TowerBriefDataNotifyOuterClass.internal_static_TowerBriefDataNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TowerBriefDataNotifyOuterClass.internal_static_TowerBriefDataNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.class, TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.Builder.class);
      }

      // Construct using TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        towerScheduleId_ = 0;

        nextScheduleChangeTime_ = 0;

        totalStarNum_ = 0;

        lastFloorIndex_ = 0;

        lastLevelIndex_ = 0;

        isFinishedEntranceFloor_ = false;

        scheduleStartTime_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TowerBriefDataNotifyOuterClass.internal_static_TowerBriefDataNotify_descriptor;
      }

      @java.lang.Override
      public TowerBriefDataNotifyOuterClass.TowerBriefDataNotify getDefaultInstanceForType() {
        return TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.getDefaultInstance();
      }

      @java.lang.Override
      public TowerBriefDataNotifyOuterClass.TowerBriefDataNotify build() {
        TowerBriefDataNotifyOuterClass.TowerBriefDataNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TowerBriefDataNotifyOuterClass.TowerBriefDataNotify buildPartial() {
        TowerBriefDataNotifyOuterClass.TowerBriefDataNotify result = new TowerBriefDataNotifyOuterClass.TowerBriefDataNotify(this);
        result.towerScheduleId_ = towerScheduleId_;
        result.nextScheduleChangeTime_ = nextScheduleChangeTime_;
        result.totalStarNum_ = totalStarNum_;
        result.lastFloorIndex_ = lastFloorIndex_;
        result.lastLevelIndex_ = lastLevelIndex_;
        result.isFinishedEntranceFloor_ = isFinishedEntranceFloor_;
        result.scheduleStartTime_ = scheduleStartTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TowerBriefDataNotifyOuterClass.TowerBriefDataNotify) {
          return mergeFrom((TowerBriefDataNotifyOuterClass.TowerBriefDataNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TowerBriefDataNotifyOuterClass.TowerBriefDataNotify other) {
        if (other == TowerBriefDataNotifyOuterClass.TowerBriefDataNotify.getDefaultInstance()) return this;
        if (other.getTowerScheduleId() != 0) {
          setTowerScheduleId(other.getTowerScheduleId());
        }
        if (other.getNextScheduleChangeTime() != 0) {
          setNextScheduleChangeTime(other.getNextScheduleChangeTime());
        }
        if (other.getTotalStarNum() != 0) {
          setTotalStarNum(other.getTotalStarNum());
        }
        if (other.getLastFloorIndex() != 0) {
          setLastFloorIndex(other.getLastFloorIndex());
        }
        if (other.getLastLevelIndex() != 0) {
          setLastLevelIndex(other.getLastLevelIndex());
        }
        if (other.getIsFinishedEntranceFloor() != false) {
          setIsFinishedEntranceFloor(other.getIsFinishedEntranceFloor());
        }
        if (other.getScheduleStartTime() != 0) {
          setScheduleStartTime(other.getScheduleStartTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TowerBriefDataNotifyOuterClass.TowerBriefDataNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TowerBriefDataNotifyOuterClass.TowerBriefDataNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int towerScheduleId_ ;
      /**
       * <code>uint32 tower_schedule_id = 1;</code>
       * @return The towerScheduleId.
       */
      @java.lang.Override
      public int getTowerScheduleId() {
        return towerScheduleId_;
      }
      /**
       * <code>uint32 tower_schedule_id = 1;</code>
       * @param value The towerScheduleId to set.
       * @return This builder for chaining.
       */
      public Builder setTowerScheduleId(int value) {
        
        towerScheduleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 tower_schedule_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTowerScheduleId() {
        
        towerScheduleId_ = 0;
        onChanged();
        return this;
      }

      private int nextScheduleChangeTime_ ;
      /**
       * <code>uint32 next_schedule_change_time = 2;</code>
       * @return The nextScheduleChangeTime.
       */
      @java.lang.Override
      public int getNextScheduleChangeTime() {
        return nextScheduleChangeTime_;
      }
      /**
       * <code>uint32 next_schedule_change_time = 2;</code>
       * @param value The nextScheduleChangeTime to set.
       * @return This builder for chaining.
       */
      public Builder setNextScheduleChangeTime(int value) {
        
        nextScheduleChangeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 next_schedule_change_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNextScheduleChangeTime() {
        
        nextScheduleChangeTime_ = 0;
        onChanged();
        return this;
      }

      private int totalStarNum_ ;
      /**
       * <code>uint32 total_star_num = 3;</code>
       * @return The totalStarNum.
       */
      @java.lang.Override
      public int getTotalStarNum() {
        return totalStarNum_;
      }
      /**
       * <code>uint32 total_star_num = 3;</code>
       * @param value The totalStarNum to set.
       * @return This builder for chaining.
       */
      public Builder setTotalStarNum(int value) {
        
        totalStarNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 total_star_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalStarNum() {
        
        totalStarNum_ = 0;
        onChanged();
        return this;
      }

      private int lastFloorIndex_ ;
      /**
       * <code>uint32 last_floor_index = 4;</code>
       * @return The lastFloorIndex.
       */
      @java.lang.Override
      public int getLastFloorIndex() {
        return lastFloorIndex_;
      }
      /**
       * <code>uint32 last_floor_index = 4;</code>
       * @param value The lastFloorIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastFloorIndex(int value) {
        
        lastFloorIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 last_floor_index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastFloorIndex() {
        
        lastFloorIndex_ = 0;
        onChanged();
        return this;
      }

      private int lastLevelIndex_ ;
      /**
       * <code>uint32 last_level_index = 5;</code>
       * @return The lastLevelIndex.
       */
      @java.lang.Override
      public int getLastLevelIndex() {
        return lastLevelIndex_;
      }
      /**
       * <code>uint32 last_level_index = 5;</code>
       * @param value The lastLevelIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastLevelIndex(int value) {
        
        lastLevelIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 last_level_index = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLevelIndex() {
        
        lastLevelIndex_ = 0;
        onChanged();
        return this;
      }

      private boolean isFinishedEntranceFloor_ ;
      /**
       * <code>bool is_finished_entrance_floor = 6;</code>
       * @return The isFinishedEntranceFloor.
       */
      @java.lang.Override
      public boolean getIsFinishedEntranceFloor() {
        return isFinishedEntranceFloor_;
      }
      /**
       * <code>bool is_finished_entrance_floor = 6;</code>
       * @param value The isFinishedEntranceFloor to set.
       * @return This builder for chaining.
       */
      public Builder setIsFinishedEntranceFloor(boolean value) {
        
        isFinishedEntranceFloor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_finished_entrance_floor = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFinishedEntranceFloor() {
        
        isFinishedEntranceFloor_ = false;
        onChanged();
        return this;
      }

      private int scheduleStartTime_ ;
      /**
       * <code>uint32 schedule_start_time = 7;</code>
       * @return The scheduleStartTime.
       */
      @java.lang.Override
      public int getScheduleStartTime() {
        return scheduleStartTime_;
      }
      /**
       * <code>uint32 schedule_start_time = 7;</code>
       * @param value The scheduleStartTime to set.
       * @return This builder for chaining.
       */
      public Builder setScheduleStartTime(int value) {
        
        scheduleStartTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 schedule_start_time = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearScheduleStartTime() {
        
        scheduleStartTime_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TowerBriefDataNotify)
    }

    // @@protoc_insertion_point(class_scope:TowerBriefDataNotify)
    private static final TowerBriefDataNotifyOuterClass.TowerBriefDataNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TowerBriefDataNotifyOuterClass.TowerBriefDataNotify();
    }

    public static TowerBriefDataNotifyOuterClass.TowerBriefDataNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TowerBriefDataNotify>
        PARSER = new com.google.protobuf.AbstractParser<TowerBriefDataNotify>() {
      @java.lang.Override
      public TowerBriefDataNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TowerBriefDataNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TowerBriefDataNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TowerBriefDataNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TowerBriefDataNotifyOuterClass.TowerBriefDataNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TowerBriefDataNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TowerBriefDataNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032TowerBriefDataNotify.proto\"\260\002\n\024TowerBr" +
      "iefDataNotify\022\031\n\021tower_schedule_id\030\001 \001(\r" +
      "\022!\n\031next_schedule_change_time\030\002 \001(\r\022\026\n\016t" +
      "otal_star_num\030\003 \001(\r\022\030\n\020last_floor_index\030" +
      "\004 \001(\r\022\030\n\020last_level_index\030\005 \001(\r\022\"\n\032is_fi" +
      "nished_entrance_floor\030\006 \001(\010\022\033\n\023schedule_" +
      "start_time\030\007 \001(\r\"M\n\005CmdId\022\010\n\004NONE\020\000\022\023\n\017E" +
      "NET_CHANNEL_ID\020\000\022\024\n\020ENET_IS_RELIABLE\020\001\022\013" +
      "\n\006CMD_ID\020\221\023\032\002\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TowerBriefDataNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TowerBriefDataNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TowerBriefDataNotify_descriptor,
        new java.lang.String[] { "TowerScheduleId", "NextScheduleChangeTime", "TotalStarNum", "LastFloorIndex", "LastLevelIndex", "IsFinishedEntranceFloor", "ScheduleStartTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
